print("Hello How are you there?")
name = input("What is your name:")
print("Its nice to meet you "+name)
age = input("whats your age:")
print("The Length of your name is: "+ str(len(name)))
print("you will be "+str(int(age)+1)+" in a year")